# TODO: Clarify whether names should be `tag` or `version`
name: Aptos LC - Create Patched Release PR

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'release or hotfix'
        type: choice
        options:
          - release
          - hotfix
        required: true
      # Tag to patch, e.g. `aptos-node-v1.14.0`
      tag:
        description: 'Release tag patched'
        required: true

jobs:
  release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.type }}/${{ inputs.tag }}-patched

      - name: Edit tag in README.md
        run: |
          echo "Dummy change" >> Cargo.toml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Release ${{ inputs.tag }}-patched"
          branch: "${{ inputs.type }}/${{ inputs.tag }}-patched"
          title: "chore: Release ${{ inputs.version }}"
          base: "${{ inputs.type == 'hotfix' && 'release/${{ inputs.tag }}' || 'release' }}:"
          commit-message: "chore: Release ${{ inputs.tag }}"

