name: Aptos LC - Create Patched Release PR

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'release or hotfix'
        type: choice
        options:
          - release
          - hotfix
        required: true
      # Tag version to patch, e.g. `aptos-node-v1.14.0`
      version:
        description: 'Release tag patched'
        required: true

jobs:
  release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.type }}/${{ inputs.version }}-patched

      # TODO: Need some change for the PR to be possible, so recording the version change in `PATCH_RELEASE.md` since we're not using `Cargo.toml`?
      - name: Edit tag version in README.md
        run: |
          echo "Version ${{ inputs.version }}" | tee -a PATCH_RELEASE.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: "${{ inputs.type }}/${{ inputs.version }}-patched"
          title: "chore: Release ${{ inputs.version }}"
          base: "${{ inputs.type == 'hotfix' && 'release/${{ inputs.version }}' || 'release' }}"
          commit-message: "chore: Release ${{ inputs.version }}"

