name: Aptos LC - Check for new tags and create issue

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  push:
    branches:
      - main

jobs:
  check-tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Fetch latest tag
        id: latest-tag
        run: |
          LATEST_TAG=$(curl --silent "https://api.github.com/repos/aptos-labs/aptos-core/releases" | jq -r '.[] | select(.name | ascii_downcase | contains("mainnet")) | .tag_name' | grep '^aptos-node-v' | sort -V | tail -n 1)
          # Check if there are any tags
          LOCAL_TAGS=$(git rev-list --tags --max-count=1 2>/dev/null)
          if [[ -n "$LOCAL_TAGS" ]]; then
            # If tags exist, describe the most recent tag
            CURRENT_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
            if [[ $(echo -e "$CURRENT_TAG\n$LATEST_TAG" | sort -V | tail -n 1) == $CURRENT_TAG ]]; then
              echo "The current tag is up to date."
              exit 0
            fi
          fi
          # If the current tag is not up to date, proceed to open an issue
          echo "tag=${LATEST_TAG}" | tee -a $GITHUB_OUTPUT

      - name: Set up git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          #- name: Add upstream remote
          #  run: |
          #    git remote add upstream "${{ github.server_url }}/aptos-labs/aptos-core.git"
          #    git fetch upstream --tags

      - name: Sync tag to branch
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "${{ github.server_url }}/aptos-labs/aptos-core.git"
          source_branch: "refs/tags/${{ steps.latest-tag.outputs.tag }}"
          destination_branch: "upstream/${{ steps.latest-tag.outputs.tag }}"
          github_token: "${{ secrets.GITHUB_TOKEN }}"

            #- name: Sync repo
            #  run: |
            #    git remote add upstream ${{ github.server_url }}/aptos-labs/aptos-core.git
            #    git fetch upstream --tags
            #    git checkout tags/${{ steps.latest-tag.outputs.tag }} -b upstream/${{ steps.latest-tag.outputs.tag }} 
            #    git push origin upstream/${{ steps.latest-tag.outputs.tag }}
            #  env:
            #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #- name: repo-sync
            #  uses: repo-sync/github-sync@v2
            #  with:
            #    #source_repo: "aptos-labs/aptos-core"
            #    source_repo: "${{ github.server_url }}/aptos-labs/aptos-core.git"
            #    source_branch: "${{ steps.latest-tag.outputs.tag }}"
            #    #destination_repo: "${{ github.server_url }}/${{ github.repository }}"
            #    destination_branch: "${{ steps.latest-tag.outputs.tag }}"
            #    #github_token: ${{ secrets.REPO_TOKEN }}
            #    github_token: ${{ secrets.GITHUB_TOKEN }}

      # Note: This won't create duplicate issues, as once the latest tag branch is pushed to remote it will be the new current tag
      # Thus, the workflow will exit in the `Fetch latest tag` step as up to date
      - name: Create issue for release
        uses: JasonEtco/create-an-issue@v2
        with:
          filename: .github/ISSUE_TEMPLATE/tag_release.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ steps.latest-tag.outputs.tag }}
          UPSTREAM_URL: https://github.com/aptos-labs/aptos-core/releases/tag/${{ steps.latest-tag.outputs.tag }}
          RELEASE_PR_WORKFLOW: ${{ github.server_url }}/${{ github.repository }}/actions/workflows/aptos-light-client-patch-release-pr.yml
          RELEASE_MERGE_WORKFLOW: ${{ github.server_url }}/${{ github.repository }}/actions/workflows/aptos-light-client-patch-release-publish.yml
          WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

